lidar_pose_from_odom:
  ros__parameters:
    input_odom_topic: /Odometry
    output_pose_topic: /lidar/pose
    output_point_topic: /lidar/point
    output_odom_topic: /lidar/odom
    lidar_frame: livox_frame
    base_frame: base_link
    publish_tf: false
    output_base_frame: false
    lidar_to_base_xyz: [0.0, 0.0, 0.0]
    lidar_to_base_rpy: [0.0, 0.0, 0.0]
    log_period_sec: 1.0
